### ISSUE TITLE
chef-zero provisioner looks for Chef Server URL and fails

### ISSUE THREAD

**Issue by scarolan** [schubergphilis/vagrant-chef-zero#61]
When I try to use this provisioner with Vagrant, I get the following errors.  Why is it looking for a server URL?  Shouldn't it default to something like localhost:8889?

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

chef client provisioner:
* Chef Server URL must be populated.
* Validation key path must be valid path to your Chef Server validation key.
```

My vagrant plugin list:
vagrant-aws (0.5.0)
vagrant-berkshelf (4.0.1)
vagrant-cachier (1.1.0)
vagrant-chef-zero (0.7.1)
vagrant-hostsupdater (0.0.11)
vagrant-ohai (0.1.7)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.4, system)
vagrant-vmware-fusion (3.1.2)

The relevant part of my Vagrantfile:
    w.vm.provision :chef_client do |chef|
      chef.node_name = config.vm.hostname
      chef.run_list = [
        "recipe[training-laptop::default]"
      ]
    end

**Comment by rory** [comment]
I am also getting this problem on Vagrant 1.7.2

**Comment by ismailfaruqi** [comment]
I have this issue too... still looking for the solution...

**Comment by miguelaferreira** [comment]
Same here :-1:

**Comment by Paxa** [comment]
@ismailfaruqi, it's here https://github.com/miguelaferreira/vagrant-chef-zero/commit/ee2b8df81803c4e56c433a3ad1e4347d7084f519

**Comment by miguelaferreira** [comment]
@ismailfaruqi @Paxa, IMHO a better fix by @wzin here a48312b

**Comment by djpate** [comment]
I'm still getting this error on vagrant 1.7.2 

```➜  vagrant_vms  vagrant plugin list
vagrant-berkshelf (4.0.3)
vagrant-chef-zero (0.7.1)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.3, system)
vagrant-vbguest (0.10.0)```

```➜  vagrant_vms  vagrant reload
Vagrant.require_plugin is deprecated and has no effect any longer.
Use `vagrant plugin` commands to manage plugins. This warning will
be removed in the next version of Vagrant.
There are errors in the configuration of this machine. Please fix
the following errors and try again:

chef client provisioner:
* Chef Server URL must be populated.
* Validation key path must be valid path to your Chef Server validation key.
```

**Comment by miguelaferreira** [comment]
A new gem with the latest fixes has not yet been released. Our bad!
We will work on getting that out.

Meanwhile, could you please build from source and try again?

1) clone the repo
2) in the repo do: `gem build vagrant-chef-zero.gemspec`
3) in the repo do: `vagrant plugin install vagrant-chef-zero-0.7.1.gem`

**Comment by miguelaferreira** [comment]
A new gem was released last Friday that contains the fixes for this issue.
Closing the issue.

**Comment by lukas0krupa** [comment]
@miguelaferreira I saw that there were version 4.2.2 of chef-zero gem from 19 May. Is that version that have this fixed ?

I currently have version 4.2.3, but issue appears again (chef solo/zero provisioner ask for chef server url)

**Comment by miguelaferreira** [comment]
Hi @lukas0krupa 
The fix I mentioned was in `vagrant-chef-zero`gem (version 1.0.1), not `chef-zero` gem.
