### ISSUE TITLE
Cant install on OSX 10.11.2 with Vagrant 1.8.1

### ISSUE THREAD

**Issue by priorityinterrupt** [schubergphilis/vagrant-chef-zero#75]
I am struggling to install the vagrant-chef-zero plugin on OSX due to net-ssh compatibility issues.  
 
    $ vagrant plugin install vagrant-chef-zero
    Installing the 'vagrant-chef-zero' plugin. This can take a few minutes... 
    The plugin(s) can't be installed due to the version conflicts below.
    This means that the plugins depend on a library version that conflicts
    with other plugins or Vagrant itself, creating an impossible situation
    where Vagrant wouldn't be able to load the plugins.

    You can fix the issue by either removing a conflicting plugin or
    by contacting a plugin author to see if they can address the conflict.

    Vagrant could not find compatible versions for gem "net-ssh":
      In Gemfile:
      vagrant (= 1.8.1) ruby depends on
      net-ssh (~> 3.0.1) ruby

    vagrant (= 1.8.1) ruby depends on
      net-scp (~> 1.1.0) ruby depends on
        net-ssh (>= 2.6.5) ruby

    vagrant (= 1.8.1) ruby depends on
      net-scp (~> 1.1.0) ruby depends on
        net-ssh (>= 2.6.5) ruby

    vagrant-chef-zero (>= 0) ruby depends on
      net-ssh (~> 2.6.6) ruby

Here is some system information:

      vagrant version && vagrant plugin list
      Installed Version: 1.8.1
      Latest Version: 1.8.1

      You're running an up-to-date version of Vagrant!
      vagrant-berkshelf (4.1.0)
      vagrant-omnibus (1.4.1)
      vagrant-share (1.1.5, system)
      vagrant-vbguest (0.11.0)
      vagrant-vmware-fusion (4.0.5)

    $ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.11.2
    BuildVersion:	15C50

**Comment by mlawson1986** [comment]
I'm having the same issue on Ubuntu 15.10

vagrant version && vagrant plugin list
Installed Version: 1.8.1
Latest Version: 1.8.1
 
You're running an up-to-date version of Vagrant!
vagrant-berkshelf (4.1.0)
vagrant-omnibus (1.4.1)
vagrant-share (1.1.5, system)
vagrant-vbguest (0.11.0)

**Comment by miguelaferreira** [comment]
Hi guys, I haven't been using or maintaining this plugin for a while now.
I've had this same issue with other tools/gems. I will investigate if we can upgrade our dependencies and release a new gem.

**Comment by miguelaferreira** [comment]
The latest version of vagrant requires `net-ssh (~> 3.0.1)` and the latest version of the chef gem requires `net-ssh (~> 2.6)`, so there is no easy way out of this dependency problem. I will try to get rid of the chef gem, but I'm not sure that it will work.

**Comment by miguelaferreira** [comment]
I got rid of the `chef`gem, but with it also the ability to upload environments and roles in `.rb` format. I'm now running system tests to see if that will work. If it does I'll make a PR and will ask you guys to build and install from source and run some more tests.

**Comment by miguelaferreira** [comment]
ping @mlawson1986 @priorityinterrupt @zakcrawford @j00p34 

I've just released v2.0.0 of to rubygems.org. Thanks for your help and patience.

**Comment by mlawson1986** [comment]
Thanks! Working now!
